export interface Country {
    code: string;
    name: string;
    countryCode: string;
  }
  
  export const AFRICAN_COUNTRY_CODES: Country[] = [
    { code: 'DZ', name: 'Algeria', countryCode: '+213' },
    { code: 'AO', name: 'Angola', countryCode: '+244' },
    { code: 'BJ', name: 'Benin', countryCode: '+229' },
    { code: 'BW', name: 'Botswana', countryCode: '+267' },
    { code: 'BF', name: 'Burkina Faso', countryCode: '+226' },
    { code: 'BI', name: 'Burundi', countryCode: '+257' },
    { code: 'CM', name: 'Cameroon', countryCode: '+237' },
    { code: 'CV', name: 'Cape Verde', countryCode: '+238' },
    { code: 'CF', name: 'C A R', countryCode: '+236' },
    { code: 'TD', name: 'Chad', countryCode: '+235' },
    { code: 'KM', name: 'Comoros', countryCode: '+269' },
    { code: 'CD', name: 'Congo-Brazzaville', countryCode: '+242' },
    { code: 'CG', name: 'Congo-Kinshasa', countryCode: '+243' },
    { code: 'DJ', name: 'Djibouti', countryCode: '+253' },
    { code: 'EG', name: 'Egypt', countryCode: '+20' },
    { code: 'GQ', name: 'Equatorial Guinea', countryCode: '+240' },
    { code: 'ER', name: 'Eritrea', countryCode: '+291' },
    { code: 'ET', name: 'Ethiopia', countryCode: '+251' },
    { code: 'GA', name: 'Gabon', countryCode: '+241' },
    { code: 'GM', name: 'Gambia', countryCode: '+220' },
    { code: 'GH', name: 'Ghana', countryCode: '+233' },
    { code: 'GN', name: 'Guinea', countryCode: '+224' },
    { code: 'GW', name: 'Guinea-Bissau', countryCode: '+245' },
    { code: 'KE', name: 'Kenya', countryCode: '+254' },
    { code: 'LS', name: 'Lesotho', countryCode: '+266' },
    { code: 'LR', name: 'Liberia', countryCode: '+231' },
    { code: 'LY', name: 'Libya', countryCode: '+218' },
    { code: 'MG', name: 'Madagascar', countryCode: '+261' },
    { code: 'MW', name: 'Malawi', countryCode: '+265' },
    { code: 'ML', name: 'Mali', countryCode: '+223' },
    { code: 'MR', name: 'Mauritania', countryCode: '+222' },
    { code: 'MU', name: 'Mauritius', countryCode: '+230' },
    { code: 'MA', name: 'Morocco', countryCode: '+212' },
    { code: 'MZ', name: 'Mozambique', countryCode: '+258' },
    { code: 'NA', name: 'Namibia', countryCode: '+264' },
    { code: 'NE', name: 'Niger', countryCode: '+227' },
    { code: 'NG', name: 'Nigeria', countryCode: '+234' },
    { code: 'RW', name: 'Rwanda', countryCode: '+250' },
    { code: 'ST', name: 'São Tomé and Prín', countryCode: '+239' },
    { code: 'SN', name: 'Senegal', countryCode: '+221' },
    { code: 'SC', name: 'Seychelles', countryCode: '+248' },
    { code: 'SL', name: 'Sierra Leone', countryCode: '+232' },
    { code: 'SO', name: 'Somalia', countryCode: '+252' },
    { code: 'ZA', name: 'South Africa', countryCode: '+27' },
    { code: 'SS', name: 'South Sudan', countryCode: '+211' },
    { code: 'SD', name: 'Sudan', countryCode: '+249' },
    { code: 'TZ', name: 'Tanzania', countryCode: '+255' },
    { code: 'TG', name: 'Togo', countryCode: '+228' },
    { code: 'TN', name: 'Tunisia', countryCode: '+216' },
    { code: 'UG', name: 'Uganda', countryCode: '+256' },
    { code: 'ZM', name: 'Zambia', countryCode: '+260' },
    { code: 'ZW', name: 'Zimbabwe', countryCode: '+263' }
  ];