spring:
  h2:
    console:
      enabled: 
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

    
app:
  url: /insurance-backend
  insdeployAdmin: 'test-admin'
  insdeployToken: 'test-admin-P@ss'
  insdeployContact: '+27733353882'
  notifications:
    notificationsAppName: 'Insurance Portal UAT'
    twilioAccountSid: 'ACe45e6a24671da4bbb978dfabb085436d'
    twilioAuthToken: '68fc7f1f55d1b7c4ffb04d99e2c7747a'
    twilioSourceNumber: '+27600868713'
    smsEnabled: true
    mailerSendApi: 'mlsn.3f20f0d53653cf4c610a5383935fc2df8e6ca40e6cedf5eaedfde30083692c43'
    fromEmail: 'no-reply@myinsuretechonline.co.za'    
    
    
jwtTokenHeader: Authorization
jwtSecret: app-secret
jwtExpiration: 604800

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
google:
  recaptcha:
    key:
      enabled: false
payfast:
   merchantId: '10000100'
   merchantKey: '46f0cd694581a'
   payfastUrl: 'https://sandbox.payfast.co.za/eng/process'
   secretKey: 'jt7NOE43FZPn'
   replyUrl: 'https://uat.myinsuretechonline.co.za/policies'
   baseAppUrl: 'https://uat.myinsuretechonline.co.za/insurance-backend/'
   domains: ['www.payfast.co.za','sandbox.payfast.co.za','w1w.payfast.co.za','w2w.payfast.co.za']
   validationUrl: 'https://sandbox.payfast.co.za/eng/query/validate'
      
logging:
  level:
    com.earmitage: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    #org.springframework.security: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: '/swagger-ui.html'
api-docs.path: '/v3/api-docs'